# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20161023_0702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postjj',
            new_name='Postjj1',
        ),
    ]
