# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20161023_0710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postjj1',
            new_name='Post',
        ),
    ]
