# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-30 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordA1',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 12, 13, 44, 648000), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passwordA2',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 12, 13, 51, 70000), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passwordA3',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 12, 13, 59, 809000), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passwordQ1',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 12, 14, 4, 969000), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passwordQ2',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 12, 14, 9, 631000), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passwordQ3',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 12, 14, 12, 141000), max_length=200),
            preserve_default=False,
        ),
    ]
